// real_estate_search_paths.js -- searchable path config for realEstate Thingas.
//
// Each path can become a code/connector/workflow Thinga later. For now this is
// the stable registry of the ways we search for properties and resolve identity.

export const PROPERTY_SEARCH_WORKFLOWS = [
  "New MLS/RESO active listings",
  "New MLS price drops",
  "MLS back-on-market",
  "MLS expired listings",
  "MLS withdrawn listings",
  "MLS canceled listings",
  "MLS long days-on-market",
  "MLS vacant remarks",
  "MLS estate/probate remarks",
  "MLS fixer/as-is remarks",
  "RentCast new-for-sale listings",
  "RentCast price-reduced listings",
  "RentCast stale listings",
  "Zillow/Redfin-equivalent via RESO feed",
  "Broker IDX feed if licensed",
  "Realtor association MLS export",
  "Listing agent inventory watch",
  "Investor-owned listing watch",
  "FSBO listing feeds",
  "Craigslist / marketplace manual-review queue",
  "Code violations",
  "Blight tickets",
  "Vacant property registry",
  "Rental inspection failures",
  "Certificate of occupancy failures",
  "Fire inspection violations",
  "Unsafe structure notices",
  "Demolition orders",
  "Nuisance abatement records",
  "Board-up permits",
  "Building permits",
  "Expired permits",
  "Open permits older than 180 days",
  "Stop-work orders",
  "Roofing permits",
  "Electrical permits",
  "Plumbing permits",
  "HVAC permits",
  "Commercial alteration permits",
  "Owner-builder permits",
  "Tax delinquency rolls",
  "Tax lien sale lists",
  "Sheriff sale lists",
  "Foreclosure notices",
  "Notice of default",
  "Notice of trustee sale",
  "Lis pendens filings",
  "Auction calendars",
  "Bankruptcy property filings",
  "REO/bank-owned records",
  "Absentee owner parcels",
  "Out-of-state owner parcels",
  "Corporate-owned parcels",
  "LLC-owned single-family parcels",
  "Trust-owned parcels",
  "Owner mailing address mismatch",
  "Multiple properties same owner",
  "High equity + absentee",
  "Low assessed value + high ARV",
  "Old purchase date + no mortgage",
  "Probate court filings",
  "Estate transfers",
  "Quitclaim deeds",
  "Interfamily transfers",
  "Divorce filings with property",
  "Guardianship/conservatorship cases",
  "Heirship records",
  "Death records matched to owner",
  "Returned mail / bad mailing address",
  "Owner age + long ownership",
  "Utility shutoff lists where public",
  "Water shutoff liens",
  "Sewer liens",
  "Weed/grass liens",
  "Trash liens",
  "Municipal special assessments",
  "HOA lien filings",
  "Mechanic's liens",
  "Contractor dispute filings",
  "Eviction filings",
  "Rental license registry",
  "Expired rental licenses",
  "Landlord violation lists",
  "Section 8 inspection failure",
  "Tenant complaint records",
  "Short-term rental permits",
  "Short-term rental violations",
  "STR permit expirations",
  "Multi-family inspection records",
  "Lead paint violation records",
  "Industrial facility records",
  "EPA/FRS facility matches",
  "Business license records at property",
  "Alcohol/tobacco/license records",
  "Health inspection failures",
  "Commercial occupancy permits",
  "Zoning variance applications",
  "Planning commission agendas",
  "Rezoning applications",
  "Parcel split/lot consolidation records",
];

export const INSTANT_MARKET_WORKFLOWS = [
  "MLS/RESO Web API",
  "Broker IDX feed",
  "RentCast sale listings endpoint",
  "CoreLogic/Trestle data distribution",
  "SimplyRETS feed",
  "Listing-agent RSS/email alerts",
  "Saved-search inbox parser",
  "County recording watch",
  "Brokerage website sitemap watcher",
  "Price-change watcher every 10-30 minutes",
];

export const IDENTITY_CONTACT_WORKFLOWS = [
  "Parcel address -> county assessor -> owner name",
  "Parcel address -> tax roll -> taxpayer name",
  "Parcel address -> APN -> owner mailing address",
  "APN -> recorder deeds -> grantee",
  "APN -> mortgage record -> borrower",
  "APN -> tax bill mailing address",
  "Owner name -> other owned parcels",
  "Owner mailing address -> absentee flag",
  "Owner mailing address -> return-mail risk",
  "Owner name + county -> recorder history",
  "LLC owner -> state Secretary of State",
  "LLC owner -> registered agent",
  "LLC owner -> principal office",
  "LLC owner -> annual report",
  "LLC owner -> manager/member if public",
  "LLC address -> business license",
  "LLC name -> permit applicant",
  "LLC name -> contractor license",
  "LLC name -> court filings",
  "LLC name -> UCC filings",
  "Property address -> business license at address",
  "Property address -> permit applicant",
  "Property address -> inspection contact",
  "Property address -> fire inspection contact",
  "Property address -> health inspection contact",
  "Property address -> rental license owner",
  "Property address -> short-term rental permit owner",
  "Property address -> code violation responsible party",
  "Property address -> nuisance abatement contact",
  "Property address -> zoning application applicant",
  "For-sale listing -> listing agent name",
  "For-sale listing -> listing agent phone",
  "For-sale listing -> listing agent email",
  "Listing brokerage -> office phone",
  "Listing agent name -> license lookup",
  "Agent license -> brokerage",
  "Agent license -> public phone/email",
  "MLS listing -> co-listing agent",
  "Listing remarks -> owner/occupant clue",
  "Price drop -> agent outreach task",
  "Owner name + address -> BatchData skip trace",
  "Owner name + mailing address -> skip trace",
  "APN + address -> BatchData property skip trace",
  "LLC + registered agent -> business phone source",
  "Business name -> official business license phone",
  "Business name -> EPA/industrial facility match",
  "Business name -> permit/inspection contact",
  "Business name -> website/contact page manual review",
  "Phone found -> reverse match to owner/entity",
  "Email found -> domain/entity match and confidence score",
];

export function buildSearchPlan({ market = "any", includePaid = false } = {}) {
  const property = PROPERTY_SEARCH_WORKFLOWS.map((name, i) => ({
    id: `property-path-${String(i + 1).padStart(3, "0")}`,
    kind: "realEstate",
    type: "workflow",
    group: "property_search",
    market,
    name,
  }));
  const instant = INSTANT_MARKET_WORKFLOWS.map((name, i) => ({
    id: `instant-market-${String(i + 1).padStart(2, "0")}`,
    kind: "realEstate",
    type: "workflow",
    group: "instant_market",
    market,
    cadence: i === 0 || i === 2 ? "10_minutes" : "configured",
    name,
  }));
  const identity = IDENTITY_CONTACT_WORKFLOWS
    .filter((name) => includePaid || !/BatchData|skip trace/i.test(name))
    .map((name, i) => ({
      id: `identity-path-${String(i + 1).padStart(3, "0")}`,
      kind: "realEstate",
      type: "workflow",
      group: "identity_contact",
      market,
      name,
    }));
  return { property, instant, identity };
}

